### ISSUE TITLE
Marvel API

### ISSUE THREAD

**Issue by Bhoward19** [CSneed7/project-1#2]
## User Story
As a user I want to find all comics associated with my favorite comic book character that I am searching for and I want to see what is available for purchase all from one location.

##Task
Marvel Characters Searchable via Marvel API

## Acceptance Criteria
- [ ] Gain access key to Marvel API
- [ ] Setup and test AJAX call
- [ ] Run console.response to assess data obtainable from API
- [ ] Find variable applicable to searching Marvel Characters
