### ISSUE TITLE
EBay API

### ISSUE THREAD

**Issue by Bhoward19** [CSneed7/project-1#3]
## Task
Marvel Comics Searchable via EBay API

## Acceptance Criteria
- [ ] Gain access key to Marvel API
- [ ] Setup and test AJAX call
- [ ] Run console.response to assess data obtainable from API
