### ISSUE TITLE
IMDB API attached

### ISSUE THREAD

**Issue by Bhoward19** [CSneed7/project-1#6]
## Task
Marvel Movies Searchable via IMDB API

## Acceptance Criteria
- [ ] Gain access key to IMDB API
- [ ] Setup and test AJAX call
- [ ] Run console.response to assess data obtainable from API
- [ ] Find variable applicable to searching Marvel Comic Movie Characters
